name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop, release/* ]

permissions:
  contents: read

jobs:
  build:
    name: Lint, Type-Check, and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

      - name: Type Check
        run: bun run typecheck

      - name: Test
        run: bun run test -- --run

  build-example:
    name: Lint, Type-Check, and Test (example)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

      # - name: Type Check
      #   run: bun run typecheck

      - name: Build
        run: bun run build-only
